package net.tap5.mls.constants;

import java.util.HashMap;
import java.util.Map;

public class GoogleLanguagesCodes {
	private static String langs[] = {
		"AA", "Afar",
		"AB", "Abkhazian",
		"AF", "Afrikaans",
		"AM", "Amharic",
		"AR", "Arabic",
		"AS", "Assamese",
		"AY", "Aymara",
		"AZ", "Azerbaijani",
		"BA", "Bashkir",
		"BE", "Belarusian",
		"BG", "Bulgarian",
		"BH", "Bihari",
		"BI", "Bislama",
		"BN", "Bengali",
		"BO", "Tibetan",
		"BR", "Breton",
		"BS", "Bosnian",
		"CEB", "Cebuano",
		"CA", "Catalan",
		"CO", "Corsican",
		"CS", "Czech",
		"CY", "Welsh",
		"DA", "Danish",
		"DE", "German",
		"DZ", "Bhutani",
		"EL", "Greek",
		"EN", "English",
		"EO", "Esperanto",
		"ES", "Spanish",
		"ET", "Estonian",
		"EU", "Basque",
		"FA", "Persian",
		"FI", "Finnish",
		"FJ", "Fiji",
		"FO", "Faeroese",
		"FR", "French",
		"FY", "Frisian",
		"GA", "Irish",
		"GD", "Gaelic",
		"GL", "Galician",
		"GN", "Guarani",
		"GU", "Gujarati",
		"HA", "Hausa",
		"HI", "Hindi",
		"HR", "Croatian",
		"HU", "Hungarian",
		"HY", "Armenian",
		"IA", "Interlingua",
		"IE", "Interlingue",
		"IK", "Inupiak",
		"IN", "Indonesian",
		"IS", "Icelandic",
		"IT", "Italian",
		"IW", "Hebrew",
		"JA", "Japanese",
		"JI", "Yiddish",
		"JW", "Javanese",
		"KA", "Georgian",
		"KK", "Kazakh",
		"KL", "Greenlandic",
		"KM", "Cambodian",
		"KN", "Kannada",
		"KO", "Korean",
		"KS", "Kashmiri",
		"KU", "Kurdish",
		"KY", "Kirghiz",
		"LA", "Latin",
		"LN", "Lingala",
		"LO", "Laothian",
		"LT", "Lithuanian",
		"LV", "Latvian",
		"MG", "Malagasy",
		"MI", "Maori",
		"MK", "Macedonian",
		"ML", "Malayalam",
		"MN", "Mongolian",
		"MO", "Moldavian",
		"MR", "Marathi",
		"MS", "Malay",
		"MT", "Maltese",
		"MY", "Burmese",
		"NA", "Nauru",
		"NE", "Nepali",
		"NL", "Dutch",
		"NO", "Norwegian",
		"OC", "Occitan",
		"OM", "Oromo",
		"OR", "Oriya",
		"PA", "Punjabi",
		"PL", "Polish",
		"PS", "Pashto",
		"PT", "Portuguese",
		"QU", "Quechua",
		"RM", "Rhaeto-Romance",
		"RN", "Kirundi",
		"RO", "Romanian",
		"RU", "Russian",
		"RW", "Kinyarwanda",
		"SA", "Sanskrit",
		"SD", "Sindhi",
		"SG", "Sangro",
		"SH", "Serbo-Croatian",
		"SI", "Singhalese",
		"SK", "Slovak",
		"SL", "Slovenian",
		"SM", "Samoan",
		"SN", "Shona",
		"SO", "Somali",
		"SQ", "Albanian",
		"SR", "Serbian",
		"SS", "Siswati",
		"ST", "Sesotho",
		"SU", "Sudanese",
		"SV", "Swedish",
		"SW", "Swahili",
		"TA", "Tamil",
		"TE", "Tegulu",
		"TG", "Tajik",
		"TH", "Thai",
		"TI", "Tigrinya",
		"TK", "Turkmen",
		"TL", "Tagalog",
		"TL", "Filipino",
		"TN", "Setswana",
		"TO", "Tonga",
		"TR", "Turkish",
		"TS", "Tsonga",
		"TT", "Tatar",
		"TW", "Twi",
		"UK", "Ukrainian",
		"UR", "Urdu",
		"UZ", "Uzbek",
		"VI", "Vietnamese",
		"VO", "Volapuk",
		"WO", "Wolof",
		"XH", "Xhosa",
		"YO", "Yoruba",
		"ZH", "Chinese",
		"ZU", "Zulu",
		"HT", "Haitian_creole",
		"HMN", "Hmong",
		"IG", "Igbo",
		"KM", "Khmer",
		"LO", "Lao",
		"TE", "Telugu"};

	private static Map<String, String> map;
	private static Map<String, String> map_;
	static {
		map = new HashMap<>();
		map_ = new HashMap<>();

		for (int i = 0; i < langs.length; i += 2) {
			String code = langs[i].toLowerCase();
			map.put(langs[i + 1], code);
			map_.put(code, langs[i + 1]);
		}
	}

	public static String getCode(String language) {
		return map.get(language);
	}

	public static String getLanguage(String code) {
		return map_.get(code);
	}
}
